version: 2
registries:
  artifactory-pypi:
    type: python-index
    url: https://test.pypi.org/simple/
    username: ${{ secrets.POETRY_HTTP_BASIC_PYPI_USERNAME }}
    password: ${{ secrets.POETRY_HTTP_BASIC_PYPI_PASSWORD }}
    replaces-base: false
updates:
  # Handles Poetry
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "22:00"
    allow:
      - dependency-name: "*"
        dependency-type: "all"
    labels:
      - "dependabot: pip"
      - "dependabot: version-bumped"
